<a href="https://colab.research.google.com/github/Harsh4584/ML-Lab/blob/main/EXP_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/ML_LAB/loan_prediction_dataset.csv")
df.head()

,Age,Income,Credit_Score,Loan_Amount,Loan_Term,Employment_Status,Loan_Approved
0,56,81788,334,15022,48,Employed,0
1,69,102879,781,21013,24,Self-Employed,1
2,46,58827,779,39687,60,Self-Employed,0
3,32,127188,364,16886,24,Unemployed,0
4,60,25655,307,26256,36,Unemployed,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                2000 non-null   int64
 1   Income             2000 non-null   int64
 2   Credit_Score       2000 non-null   int64
 3   Loan_Amount        2000 non-null   int64
 4   Loan_Term          2000 non-null   int64
 5   Employment_Status  2000 non-null   object
 6   Loan_Approved      2000 non-null   int64
dtypes: int64(6), object(1)
memory usage: 109.5+ KB

In [6]:
df.describe()

,Age,Income,Credit_Score,Loan_Amount,Loan_Term,Loan_Approved
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000
mean,43.805500,84533.585000,577.055000,25460.315000,35.47800,0.171000
std,14.929203,37771.169751,157.525951,14116.737774,16.98587,0.376603
min,18.000000,20155.000000,300.000000,1060.000000,12.00000,0.000000
25%,31.000000,50925.250000,440.000000,13444.250000,24.00000,0.000000
50%,44.000000,84073.500000,578.500000,25446.000000,36.00000,0.000000
75%,56.000000,117523.250000,715.250000,37949.250000,48.00000,0.000000
max,69.000000,149992.000000,849.000000,49994.000000,60.00000,1.000000

In [7]:
df.isnull().sum()

Age                  0
Income               0
Credit_Score         0
Loan_Amount          0
Loan_Term            0
Employment_Status    0
Loan_Approved        0
dtype: int64

In [8]:
df = pd.get_dummies(
    df,
    columns=['Employment_Status'],
    dtype=int
)

In [9]:
df.head()

,Age,Income,Credit_Score,Loan_Amount,Loan_Term,Loan_Approved,Employment_Status_Employed,Employment_Status_Self-Employed,Employment_Status_Unemployed
0,56,81788,334,15022,48,0,1,0,0
1,69,102879,781,21013,24,1,0,1,0
2,46,58827,779,39687,60,0,0,1,0
3,32,127188,364,16886,24,0,0,0,1
4,60,25655,307,26256,36,0,0,0,1

In [11]:
df['Loan_Amount'] = (
    df['Loan_Amount'] - df['Loan_Amount'].min()
) / (
    df['Loan_Amount'].max() - df['Loan_Amount'].min()
)

In [12]:
n = int(0.8 * len(df))

train = df[:n]
test = df[n:]


print("Training Data:")
print(train.head())

print("Testing Data:")
print(test.head())

print("Training Shape:", train.shape)
print("Testing Shape:", test.shape)

Training Data:
   Age  Income  Credit_Score  Loan_Amount  Loan_Term  Loan_Approved  \
0   56   81788           334     0.285323         48              0
1   69  102879           781     0.407753         24              1
2   46   58827           779     0.789369         60              0
3   32  127188           364     0.323415         24              0
4   60   25655           307     0.514898         36              0

   Employment_Status_Employed  Employment_Status_Self-Employed  \
0                           1                                0
1                           0                                1
2                           0                                1
3                           0                                0
4                           0                                0

   Employment_Status_Unemployed
0                             0
1                             0
2                             0
3                             1
4                             1
Testing Data:
      Age  Income  Credit_Score  Loan_Amount  Loan_Term  Loan_Approved  \
1600   41  129153           770     0.833429         60              0
1601   36   89184           431     0.617914         36              0
1602   25   67945           386     0.424572         48              0
1603   48   33140           482     0.506212         48              0
1604   38  146468           667     0.019353         60              1

      Employment_Status_Employed  Employment_Status_Self-Employed  \
1600                           0                                1
1601                           1                                0
1602                           1                                0
1603                           0                                1
1604                           1                                0

      Employment_Status_Unemployed
1600                             0
1601                             0
1602                             0
1603                             0
1604                             0
Training Shape: (1600, 9)
Testing Shape: (400, 9)